kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."zot.example.org:5000"]
      endpoint = ["http://zot.example.org:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            authentication-config: /etc/kubernetes/pki/auth-config.yaml
            #v: "6"
    extraMounts:
      - hostPath: /etc/kubernetes
        containerPath: /etc/kubernetes
      - hostPath: /etc/kubernetes/hosts
        containerPath: /etc/hosts
        readOnly: true
  - role: worker
    extraMounts:
      - hostPath: ./k8s-image-cred-spire-identity-exchange
        containerPath: /credential-plugins/k8s-image-cred-spire-identity-exchange
      - hostPath: ./tests/integration/common/credential-provider-config.yaml
        containerPath: /etc/kubernetes/credential-provider-config.yaml
      - hostPath: /etc/kubernetes/hosts
        containerPath: /etc/hosts
        readOnly: true
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            image-credential-provider-config: /etc/kubernetes/credential-provider-config.yaml
            image-credential-provider-bin-dir: /credential-plugins
  - role: worker
    extraMounts:
      - hostPath: ./k8s-image-cred-spire-identity-exchange
        containerPath: /credential-plugins/k8s-image-cred-spire-identity-exchange
      - hostPath: ./tests/integration/common/credential-provider-config.yaml
        containerPath: /etc/kubernetes/credential-provider-config.yaml
      - hostPath: /etc/kubernetes/hosts
        containerPath: /etc/hosts
        readOnly: true
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            image-credential-provider-config: /etc/kubernetes/credential-provider-config.yaml
            image-credential-provider-bin-dir: /credential-plugins
