kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            authentication-config: /etc/kubernetes/pki/auth-config.yaml
            v: "6"
    extraMounts:
      - hostPath: /etc/kubernetes
        containerPath: /etc/kubernetes
      - hostPath: /etc/kubernetes/hosts
        containerPath: /etc/hosts
        readOnly: true
  - role: worker
  - role: worker
