// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: SpireIdentityExchangeApi.proto

package api

import (
	v1 "github.com/spiffe/spire-api-sdk/proto/spire/api/server/svid/v1"
	types "github.com/spiffe/spire-api-sdk/proto/spire/api/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GithubOIDC represents GitHub OIDC authentication method
type GithubOIDC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GithubToken   string                 `protobuf:"bytes,1,opt,name=githubToken,proto3" json:"githubToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubOIDC) Reset() {
	*x = GithubOIDC{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubOIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubOIDC) ProtoMessage() {}

func (x *GithubOIDC) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubOIDC.ProtoReflect.Descriptor instead.
func (*GithubOIDC) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{0}
}

func (x *GithubOIDC) GetGithubToken() string {
	if x != nil {
		return x.GithubToken
	}
	return ""
}

// K8sSA represents Kubernetes Service Account authentication method
type K8SSA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K8SSAToken    string                 `protobuf:"bytes,1,opt,name=k8sSAToken,proto3" json:"k8sSAToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SSA) Reset() {
	*x = K8SSA{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SSA) ProtoMessage() {}

func (x *K8SSA) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SSA.ProtoReflect.Descriptor instead.
func (*K8SSA) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{1}
}

func (x *K8SSA) GetK8SSAToken() string {
	if x != nil {
		return x.K8SSAToken
	}
	return ""
}

// PluginAuth names one plugin in the registry and carries its bearer token.
// Wrapped in PluginAuthList so a request can carry multiple credentials —
// today the server only honors a single-element list; multi-element support
// is reserved for future stack composition.
type PluginAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pluginName must match one of cfg.Auth.Plugins[].name (e.g. "github",
	// "gitlab", "k8s_psat", or an operator-defined name).
	PluginName string `protobuf:"bytes,1,opt,name=pluginName,proto3" json:"pluginName,omitempty"`
	// token is the raw bearer token passed to the named plugin's Validate.
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginAuth) Reset() {
	*x = PluginAuth{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAuth) ProtoMessage() {}

func (x *PluginAuth) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAuth.ProtoReflect.Descriptor instead.
func (*PluginAuth) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{2}
}

func (x *PluginAuth) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *PluginAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// PluginAuthList wraps one or more PluginAuth entries. The wire format is a
// list so a future "stack" composition feature (validating multiple
// credentials against multiple plugins on one call) can land without a
// breaking proto change. The current server requires exactly one entry and
// returns Unimplemented for multi-entry requests.
type PluginAuthList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginAuth          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginAuthList) Reset() {
	*x = PluginAuthList{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginAuthList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginAuthList) ProtoMessage() {}

func (x *PluginAuthList) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginAuthList.ProtoReflect.Descriptor instead.
func (*PluginAuthList) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{3}
}

func (x *PluginAuthList) GetPlugins() []*PluginAuth {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// MintJWTSVIDRequest contains parameters for JWT-SVID issuance.
// The SPIFFE ID is derived from the workload token claims by spire-identity-exchange.
type MintJWTSVIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Intended audiences for the JWT-SVID.
	Audiences []string `protobuf:"bytes,1,rep,name=audiences,proto3" json:"audiences,omitempty"`
	// Optional. TTL in seconds. 0 means use the configured default.
	Ttl           int32 `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintJWTSVIDRequest) Reset() {
	*x = MintJWTSVIDRequest{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintJWTSVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintJWTSVIDRequest) ProtoMessage() {}

func (x *MintJWTSVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintJWTSVIDRequest.ProtoReflect.Descriptor instead.
func (*MintJWTSVIDRequest) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{4}
}

func (x *MintJWTSVIDRequest) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *MintJWTSVIDRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// ServerKeyGenRequest requests server-side key generation for X.509 SVID issuance.
// The client submits only a workload token; spire-identity-exchange generates an ECDSA
// P-256 key pair, signs a CSR, and returns both the certificate chain and the private
// key over TLS. The private key is never stored or logged by spire-identity-exchange.
type ServerKeyGenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. TTL in seconds. 0 means use the configured default.
	Ttl           int32 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerKeyGenRequest) Reset() {
	*x = ServerKeyGenRequest{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerKeyGenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerKeyGenRequest) ProtoMessage() {}

func (x *ServerKeyGenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerKeyGenRequest.ProtoReflect.Descriptor instead.
func (*ServerKeyGenRequest) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{5}
}

func (x *ServerKeyGenRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// MintCertificateRequest is the request for the MintCertificate method.
// Exactly one AuthMethod and exactly one of the three SVID request fields must be set.
type MintCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specify the authentication method.
	//
	// Types that are valid to be assigned to AuthMethod:
	//
	//	*MintCertificateRequest_GithubOIDC
	//	*MintCertificateRequest_K8SSA
	//	*MintCertificateRequest_PluginAuthList
	AuthMethod isMintCertificateRequest_AuthMethod `protobuf_oneof:"AuthMethod"`
	// CSR-based X.509 SVID issuance (default mode). Client generates the key pair and
	// submits a PKCS#10 CSR; the private key never leaves the client.
	// Ref: https://github.com/spiffe/spire-api-sdk/blob/main/proto/spire/api/server/svid/v1/svid.proto
	MintX509SVIDRequest *v1.MintX509SVIDRequest `protobuf:"bytes,3,opt,name=mintX509SVIDRequest,proto3" json:"mintX509SVIDRequest,omitempty"`
	// JWT-SVID issuance. No CSR required; specify target audiences.
	MintJWTSVIDRequest *MintJWTSVIDRequest `protobuf:"bytes,4,opt,name=mintJWTSVIDRequest,proto3" json:"mintJWTSVIDRequest,omitempty"`
	// Server-side key generation for X.509 SVID. No CSR required;
	// spire-identity-exchange generates the ECDSA P-256 key pair. Requires TLS.
	ServerKeyGenRequest *ServerKeyGenRequest `protobuf:"bytes,5,opt,name=serverKeyGenRequest,proto3" json:"serverKeyGenRequest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MintCertificateRequest) Reset() {
	*x = MintCertificateRequest{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertificateRequest) ProtoMessage() {}

func (x *MintCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertificateRequest.ProtoReflect.Descriptor instead.
func (*MintCertificateRequest) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{6}
}

func (x *MintCertificateRequest) GetAuthMethod() isMintCertificateRequest_AuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return nil
}

func (x *MintCertificateRequest) GetGithubOIDC() *GithubOIDC {
	if x != nil {
		if x, ok := x.AuthMethod.(*MintCertificateRequest_GithubOIDC); ok {
			return x.GithubOIDC
		}
	}
	return nil
}

func (x *MintCertificateRequest) GetK8SSA() *K8SSA {
	if x != nil {
		if x, ok := x.AuthMethod.(*MintCertificateRequest_K8SSA); ok {
			return x.K8SSA
		}
	}
	return nil
}

func (x *MintCertificateRequest) GetPluginAuthList() *PluginAuthList {
	if x != nil {
		if x, ok := x.AuthMethod.(*MintCertificateRequest_PluginAuthList); ok {
			return x.PluginAuthList
		}
	}
	return nil
}

func (x *MintCertificateRequest) GetMintX509SVIDRequest() *v1.MintX509SVIDRequest {
	if x != nil {
		return x.MintX509SVIDRequest
	}
	return nil
}

func (x *MintCertificateRequest) GetMintJWTSVIDRequest() *MintJWTSVIDRequest {
	if x != nil {
		return x.MintJWTSVIDRequest
	}
	return nil
}

func (x *MintCertificateRequest) GetServerKeyGenRequest() *ServerKeyGenRequest {
	if x != nil {
		return x.ServerKeyGenRequest
	}
	return nil
}

type isMintCertificateRequest_AuthMethod interface {
	isMintCertificateRequest_AuthMethod()
}

type MintCertificateRequest_GithubOIDC struct {
	GithubOIDC *GithubOIDC `protobuf:"bytes,1,opt,name=githubOIDC,proto3,oneof"`
}

type MintCertificateRequest_K8SSA struct {
	K8SSA *K8SSA `protobuf:"bytes,2,opt,name=k8sSA,proto3,oneof"`
}

type MintCertificateRequest_PluginAuthList struct {
	// Generic plugin-based authentication routed through the pkg/validator
	// registry. Same plugin pool as the REST /svid/{stack}/x509 endpoint, so a
	// single operator-configured plugin (e.g. gitlab) is usable over both
	// surfaces with no proto change. Carried as a list (currently single-
	// element) to leave room for future multi-plugin stack composition.
	PluginAuthList *PluginAuthList `protobuf:"bytes,6,opt,name=pluginAuthList,proto3,oneof"`
}

func (*MintCertificateRequest_GithubOIDC) isMintCertificateRequest_AuthMethod() {}

func (*MintCertificateRequest_K8SSA) isMintCertificateRequest_AuthMethod() {}

func (*MintCertificateRequest_PluginAuthList) isMintCertificateRequest_AuthMethod() {}

// MintCertificateResponse is the response for the MintCertificate method.
type MintCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The minted X.509 SVID. Set for CSR-based and server-side key generation requests.
	// Ref: https://github.com/spiffe/spire-api-sdk/blob/main/proto/spire/api/types/x509svid.proto
	X509Svid *types.X509SVID `protobuf:"bytes,1,opt,name=x509svid,proto3" json:"x509svid,omitempty"`
	// The minted JWT-SVID. Set for JWT-SVID issuance requests.
	// Ref: https://github.com/spiffe/spire-api-sdk/blob/main/proto/spire/api/types/jwtsvid.proto
	JwtSvid *types.JWTSVID `protobuf:"bytes,2,opt,name=jwtSvid,proto3" json:"jwtSvid,omitempty"`
	// PEM-encoded PKCS#8 private key. Set only when serverKeyGenRequest was used.
	// Treat as a secret; transmitted over TLS only and never stored or logged.
	PrivateKeyPem []byte `protobuf:"bytes,3,opt,name=privateKeyPem,proto3" json:"privateKeyPem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintCertificateResponse) Reset() {
	*x = MintCertificateResponse{}
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCertificateResponse) ProtoMessage() {}

func (x *MintCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SpireIdentityExchangeApi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCertificateResponse.ProtoReflect.Descriptor instead.
func (*MintCertificateResponse) Descriptor() ([]byte, []int) {
	return file_SpireIdentityExchangeApi_proto_rawDescGZIP(), []int{7}
}

func (x *MintCertificateResponse) GetX509Svid() *types.X509SVID {
	if x != nil {
		return x.X509Svid
	}
	return nil
}

func (x *MintCertificateResponse) GetJwtSvid() *types.JWTSVID {
	if x != nil {
		return x.JwtSvid
	}
	return nil
}

func (x *MintCertificateResponse) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

var File_SpireIdentityExchangeApi_proto protoreflect.FileDescriptor

const file_SpireIdentityExchangeApi_proto_rawDesc = "" +
	"\n" +
	"\x1eSpireIdentityExchangeApi.proto\x12\"proto.spiffe.spireidentityexchange\x1a\x1cgoogle/api/annotations.proto\x1a\x1espire/api/types/x509svid.proto\x1a\x1dspire/api/types/jwtsvid.proto\x1a#spire/api/server/svid/v1/svid.proto\".\n" +
	"\n" +
	"GithubOIDC\x12 \n" +
	"\vgithubToken\x18\x01 \x01(\tR\vgithubToken\"=\n" +
	"\x05K8sSA\x12\x1e\n" +
	"\n" +
	"k8sSAToken\x18\x01 \x01(\tR\n" +
	"k8sSATokenJ\x04\b\x02\x10\x03R\x0ek8sClusterName\"B\n" +
	"\n" +
	"PluginAuth\x12\x1e\n" +
	"\n" +
	"pluginName\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"Z\n" +
	"\x0ePluginAuthList\x12H\n" +
	"\aplugins\x18\x01 \x03(\v2..proto.spiffe.spireidentityexchange.PluginAuthR\aplugins\"D\n" +
	"\x12MintJWTSVIDRequest\x12\x1c\n" +
	"\taudiences\x18\x01 \x03(\tR\taudiences\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x05R\x03ttl\"'\n" +
	"\x13ServerKeyGenRequest\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x05R\x03ttl\"\xcd\x04\n" +
	"\x16MintCertificateRequest\x12P\n" +
	"\n" +
	"githubOIDC\x18\x01 \x01(\v2..proto.spiffe.spireidentityexchange.GithubOIDCH\x00R\n" +
	"githubOIDC\x12A\n" +
	"\x05k8sSA\x18\x02 \x01(\v2).proto.spiffe.spireidentityexchange.K8sSAH\x00R\x05k8sSA\x12\\\n" +
	"\x0epluginAuthList\x18\x06 \x01(\v22.proto.spiffe.spireidentityexchange.PluginAuthListH\x00R\x0epluginAuthList\x12_\n" +
	"\x13mintX509SVIDRequest\x18\x03 \x01(\v2-.spire.api.server.svid.v1.MintX509SVIDRequestR\x13mintX509SVIDRequest\x12f\n" +
	"\x12mintJWTSVIDRequest\x18\x04 \x01(\v26.proto.spiffe.spireidentityexchange.MintJWTSVIDRequestR\x12mintJWTSVIDRequest\x12i\n" +
	"\x13serverKeyGenRequest\x18\x05 \x01(\v27.proto.spiffe.spireidentityexchange.ServerKeyGenRequestR\x13serverKeyGenRequestB\f\n" +
	"\n" +
	"AuthMethod\"\xaa\x01\n" +
	"\x17MintCertificateResponse\x125\n" +
	"\bx509svid\x18\x01 \x01(\v2\x19.spire.api.types.X509SVIDR\bx509svid\x122\n" +
	"\ajwtSvid\x18\x02 \x01(\v2\x18.spire.api.types.JWTSVIDR\ajwtSvid\x12$\n" +
	"\rprivateKeyPem\x18\x03 \x01(\fR\rprivateKeyPem2\xc8\x01\n" +
	"\x18SpireIdentityExchangeApi\x12\xab\x01\n" +
	"\x0fMintCertificate\x12:.proto.spiffe.spireidentityexchange.MintCertificateRequest\x1a;.proto.spiffe.spireidentityexchange.MintCertificateResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/mint-certificateB1P\x01Z-github.com/spiffe/spire-identity-exchange/apib\x06proto3"

var (
	file_SpireIdentityExchangeApi_proto_rawDescOnce sync.Once
	file_SpireIdentityExchangeApi_proto_rawDescData []byte
)

func file_SpireIdentityExchangeApi_proto_rawDescGZIP() []byte {
	file_SpireIdentityExchangeApi_proto_rawDescOnce.Do(func() {
		file_SpireIdentityExchangeApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SpireIdentityExchangeApi_proto_rawDesc), len(file_SpireIdentityExchangeApi_proto_rawDesc)))
	})
	return file_SpireIdentityExchangeApi_proto_rawDescData
}

var file_SpireIdentityExchangeApi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_SpireIdentityExchangeApi_proto_goTypes = []any{
	(*GithubOIDC)(nil),              // 0: proto.spiffe.spireidentityexchange.GithubOIDC
	(*K8SSA)(nil),                   // 1: proto.spiffe.spireidentityexchange.K8sSA
	(*PluginAuth)(nil),              // 2: proto.spiffe.spireidentityexchange.PluginAuth
	(*PluginAuthList)(nil),          // 3: proto.spiffe.spireidentityexchange.PluginAuthList
	(*MintJWTSVIDRequest)(nil),      // 4: proto.spiffe.spireidentityexchange.MintJWTSVIDRequest
	(*ServerKeyGenRequest)(nil),     // 5: proto.spiffe.spireidentityexchange.ServerKeyGenRequest
	(*MintCertificateRequest)(nil),  // 6: proto.spiffe.spireidentityexchange.MintCertificateRequest
	(*MintCertificateResponse)(nil), // 7: proto.spiffe.spireidentityexchange.MintCertificateResponse
	(*v1.MintX509SVIDRequest)(nil),  // 8: spire.api.server.svid.v1.MintX509SVIDRequest
	(*types.X509SVID)(nil),          // 9: spire.api.types.X509SVID
	(*types.JWTSVID)(nil),           // 10: spire.api.types.JWTSVID
}
var file_SpireIdentityExchangeApi_proto_depIdxs = []int32{
	2,  // 0: proto.spiffe.spireidentityexchange.PluginAuthList.plugins:type_name -> proto.spiffe.spireidentityexchange.PluginAuth
	0,  // 1: proto.spiffe.spireidentityexchange.MintCertificateRequest.githubOIDC:type_name -> proto.spiffe.spireidentityexchange.GithubOIDC
	1,  // 2: proto.spiffe.spireidentityexchange.MintCertificateRequest.k8sSA:type_name -> proto.spiffe.spireidentityexchange.K8sSA
	3,  // 3: proto.spiffe.spireidentityexchange.MintCertificateRequest.pluginAuthList:type_name -> proto.spiffe.spireidentityexchange.PluginAuthList
	8,  // 4: proto.spiffe.spireidentityexchange.MintCertificateRequest.mintX509SVIDRequest:type_name -> spire.api.server.svid.v1.MintX509SVIDRequest
	4,  // 5: proto.spiffe.spireidentityexchange.MintCertificateRequest.mintJWTSVIDRequest:type_name -> proto.spiffe.spireidentityexchange.MintJWTSVIDRequest
	5,  // 6: proto.spiffe.spireidentityexchange.MintCertificateRequest.serverKeyGenRequest:type_name -> proto.spiffe.spireidentityexchange.ServerKeyGenRequest
	9,  // 7: proto.spiffe.spireidentityexchange.MintCertificateResponse.x509svid:type_name -> spire.api.types.X509SVID
	10, // 8: proto.spiffe.spireidentityexchange.MintCertificateResponse.jwtSvid:type_name -> spire.api.types.JWTSVID
	6,  // 9: proto.spiffe.spireidentityexchange.SpireIdentityExchangeApi.MintCertificate:input_type -> proto.spiffe.spireidentityexchange.MintCertificateRequest
	7,  // 10: proto.spiffe.spireidentityexchange.SpireIdentityExchangeApi.MintCertificate:output_type -> proto.spiffe.spireidentityexchange.MintCertificateResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_SpireIdentityExchangeApi_proto_init() }
func file_SpireIdentityExchangeApi_proto_init() {
	if File_SpireIdentityExchangeApi_proto != nil {
		return
	}
	file_SpireIdentityExchangeApi_proto_msgTypes[6].OneofWrappers = []any{
		(*MintCertificateRequest_GithubOIDC)(nil),
		(*MintCertificateRequest_K8SSA)(nil),
		(*MintCertificateRequest_PluginAuthList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SpireIdentityExchangeApi_proto_rawDesc), len(file_SpireIdentityExchangeApi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SpireIdentityExchangeApi_proto_goTypes,
		DependencyIndexes: file_SpireIdentityExchangeApi_proto_depIdxs,
		MessageInfos:      file_SpireIdentityExchangeApi_proto_msgTypes,
	}.Build()
	File_SpireIdentityExchangeApi_proto = out.File
	file_SpireIdentityExchangeApi_proto_goTypes = nil
	file_SpireIdentityExchangeApi_proto_depIdxs = nil
}
