// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: SpireIdentityExchangeApi.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpireIdentityExchangeApi_MintCertificate_FullMethodName = "/proto.spiffe.spireidentityexchange.SpireIdentityExchangeApi/MintCertificate"
)

// SpireIdentityExchangeApiClient is the client API for SpireIdentityExchangeApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpireIdentityExchangeApi is the gRPC service for the spire-identity-exchange API.
// It exposes the OSS SPIRE server API to workloads that cannot run a SPIRE agent.
// https://github.com/spiffe/spire-api-sdk/tree/main/proto/spire/api/server
type SpireIdentityExchangeApiClient interface {
	// MintCertificate issues a SPIFFE SVID (X.509 or JWT) for the authenticated workload.
	MintCertificate(ctx context.Context, in *MintCertificateRequest, opts ...grpc.CallOption) (*MintCertificateResponse, error)
}

type spireIdentityExchangeApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSpireIdentityExchangeApiClient(cc grpc.ClientConnInterface) SpireIdentityExchangeApiClient {
	return &spireIdentityExchangeApiClient{cc}
}

func (c *spireIdentityExchangeApiClient) MintCertificate(ctx context.Context, in *MintCertificateRequest, opts ...grpc.CallOption) (*MintCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintCertificateResponse)
	err := c.cc.Invoke(ctx, SpireIdentityExchangeApi_MintCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpireIdentityExchangeApiServer is the server API for SpireIdentityExchangeApi service.
// All implementations must embed UnimplementedSpireIdentityExchangeApiServer
// for forward compatibility.
//
// SpireIdentityExchangeApi is the gRPC service for the spire-identity-exchange API.
// It exposes the OSS SPIRE server API to workloads that cannot run a SPIRE agent.
// https://github.com/spiffe/spire-api-sdk/tree/main/proto/spire/api/server
type SpireIdentityExchangeApiServer interface {
	// MintCertificate issues a SPIFFE SVID (X.509 or JWT) for the authenticated workload.
	MintCertificate(context.Context, *MintCertificateRequest) (*MintCertificateResponse, error)
	mustEmbedUnimplementedSpireIdentityExchangeApiServer()
}

// UnimplementedSpireIdentityExchangeApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpireIdentityExchangeApiServer struct{}

func (UnimplementedSpireIdentityExchangeApiServer) MintCertificate(context.Context, *MintCertificateRequest) (*MintCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintCertificate not implemented")
}
func (UnimplementedSpireIdentityExchangeApiServer) mustEmbedUnimplementedSpireIdentityExchangeApiServer() {
}
func (UnimplementedSpireIdentityExchangeApiServer) testEmbeddedByValue() {}

// UnsafeSpireIdentityExchangeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpireIdentityExchangeApiServer will
// result in compilation errors.
type UnsafeSpireIdentityExchangeApiServer interface {
	mustEmbedUnimplementedSpireIdentityExchangeApiServer()
}

func RegisterSpireIdentityExchangeApiServer(s grpc.ServiceRegistrar, srv SpireIdentityExchangeApiServer) {
	// If the following call panics, it indicates UnimplementedSpireIdentityExchangeApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpireIdentityExchangeApi_ServiceDesc, srv)
}

func _SpireIdentityExchangeApi_MintCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpireIdentityExchangeApiServer).MintCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpireIdentityExchangeApi_MintCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpireIdentityExchangeApiServer).MintCertificate(ctx, req.(*MintCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpireIdentityExchangeApi_ServiceDesc is the grpc.ServiceDesc for SpireIdentityExchangeApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpireIdentityExchangeApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.spiffe.spireidentityexchange.SpireIdentityExchangeApi",
	HandlerType: (*SpireIdentityExchangeApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintCertificate",
			Handler:    _SpireIdentityExchangeApi_MintCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SpireIdentityExchangeApi.proto",
}
